/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pos.project;

import java.sql.*;
import Pack.*;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class PurchaseList extends javax.swing.JDialog {

    mySQLQueries mysql = new mySQLQueries();
    DefaultTableModel dtm = new DefaultTableModel();
    DBConnection db = new DBConnection();
    Statement ste = null;
    Connection con = null;
    
    public PurchaseList() {
        
        initComponents();
        
        try
        {
            con = db.GetMySQLConnection();
            createtable();
            fillpurchase();
            
            
            
        }
       catch(ClassNotFoundException cnfx)
        {
            cnfx.printStackTrace();
            System.out.print(cnfx);
        }
        
        catch(SQLException sqle)
        {
            sqle.printStackTrace();
            System.out.print(sqle);
        }
        
        catch (Exception exp)
        {
            exp.printStackTrace();
            System.out.print(exp);
        }
        
    }
    
     public void createtable()
    {
        dtm.addColumn("Purchase ID");
        dtm.addColumn("Date");
        dtm.addColumn("Supplier Name");
        dtm.addColumn("Item Name | Brand | Type");
        dtm.addColumn("Price");
        dtm.addColumn("Quantity");
        
        tblpurchaselist.setModel(dtm);
        
        setColumnWidth(0,40);
        setColumnWidth(1,40);
        setColumnWidth(2,60);
        setColumnWidth(3,300);
        setColumnWidth(4,30);
        setColumnWidth(5,10);
    }
    
    
    public void setColumnWidth(int index,int width)
    {
        DefaultTableColumnModel tcm = (DefaultTableColumnModel)tblpurchaselist.getColumnModel();
        TableColumn tc = tcm.getColumn(index);
        tc.setPreferredWidth(width);
        
    }
    
    public void fillpurchase()
    {
        String strdataitem[] = new String[6];
        String strquery[] = new String [6];
        
        try
        {
            ste = con.createStatement();
            String str  = "select * from pos_project.purchase,purchasedetail where purchase.purchaseID=purchasedetail.purchaseID ";
            
            ResultSet rs = ste.executeQuery(str);
            
            while(rs.next())
            {
                strdataitem[0] = rs.getString(1);
                strdataitem[1] = rs.getString(3);
                
                
                
                strquery = mysql.getSupplierData(rs.getString(2));
                  strdataitem[2] = strquery[0];
                  strquery = mysql.getItemData(rs.getString(7));
                  
                  strdataitem[3] = strquery[2];
                 strdataitem[4] = strquery[3];
                 strdataitem[5] = strquery[5];
                 
                 strquery = mysql.getMerchandiseData(strquery[1]);
                  
                  
                 strdataitem[3] += " | "+ mysql.getBrandName(strquery[0]);
                  strdataitem[3] += " | "+ mysql.getTypeName(strquery[1]);
                
                 
                
                 dtm.addRow(strdataitem);
            }
            tblpurchaselist.setModel(dtm);
        }
        
       catch (Exception exp)
        {
            exp.printStackTrace();
            System.out.print(exp);
        }
        
    } 
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp = new javax.swing.JScrollPane();
        tblpurchaselist = new javax.swing.JTable();
        print = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblpurchaselist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sp.setViewportView(tblpurchaselist);

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem1");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem1");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem1");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("jMenuItem1");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(print)
                .addGap(18, 18, 18)
                .addComponent(Close)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(print)
                    .addComponent(Close))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try {
            tblpurchaselist.print();
        } catch (PrinterException ex) {
            Logger.getLogger(PurchaseList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PurchaseList dialog = new PurchaseList();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JButton print;
    private javax.swing.JScrollPane sp;
    private javax.swing.JTable tblpurchaselist;
    // End of variables declaration//GEN-END:variables
}
